### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by QasimArif** [advanced-astro/astro-min#5]
Hey! Tried installing on npm run astro add astro-min, it came up with this error

 Installing dependencies...

 Command failed with exit code 1: npm install astro-min@^null
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^null" of package "astro-min@^null": Tags may not have any characters that encodeURIComponent encodes.

**Comment by rdwz** [comment]
Thank you. I published a new version, auto install should work again. 

Previous version wasn't tagged properly `npm publish --tag <beta|dev|next>`

**Comment by rdwz** [comment]
Fixed with [v1.1.0](https://www.npmjs.com/package/astro-min/v/1.1.0) https://github.com/advanced-astro/astro-min/commit/aa409d890f0f8c1e25d4201c4358056d18c8c1fd
